// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "Debug.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* LocalizationDataForGUI_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  LocalizationDataForGUI_reflection_ = NULL;
const ::google::protobuf::Descriptor* PositionInfo_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PositionInfo_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* PositionInfo_ROLE_descriptor_ = NULL;
const ::google::protobuf::Descriptor* FormationDataForGUI_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  FormationDataForGUI_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_Debug_2eproto() {
  protobuf_AddDesc_Debug_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "Debug.proto");
  GOOGLE_CHECK(file != NULL);
  LocalizationDataForGUI_descriptor_ = file->message_type(0);
  static const int LocalizationDataForGUI_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LocalizationDataForGUI, particles_),
  };
  LocalizationDataForGUI_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      LocalizationDataForGUI_descriptor_,
      LocalizationDataForGUI::default_instance_,
      LocalizationDataForGUI_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LocalizationDataForGUI, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LocalizationDataForGUI, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(LocalizationDataForGUI));
  PositionInfo_descriptor_ = file->message_type(1);
  static const int PositionInfo_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PositionInfo, x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PositionInfo, y_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PositionInfo, role_),
  };
  PositionInfo_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      PositionInfo_descriptor_,
      PositionInfo::default_instance_,
      PositionInfo_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PositionInfo, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PositionInfo, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(PositionInfo));
  PositionInfo_ROLE_descriptor_ = PositionInfo_descriptor_->enum_type(0);
  FormationDataForGUI_descriptor_ = file->message_type(2);
  static const int FormationDataForGUI_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FormationDataForGUI, positions_),
  };
  FormationDataForGUI_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      FormationDataForGUI_descriptor_,
      FormationDataForGUI::default_instance_,
      FormationDataForGUI_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FormationDataForGUI, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FormationDataForGUI, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(FormationDataForGUI));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_Debug_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    LocalizationDataForGUI_descriptor_, &LocalizationDataForGUI::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    PositionInfo_descriptor_, &PositionInfo::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    FormationDataForGUI_descriptor_, &FormationDataForGUI::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_Debug_2eproto() {
  delete LocalizationDataForGUI::default_instance_;
  delete LocalizationDataForGUI_reflection_;
  delete PositionInfo::default_instance_;
  delete PositionInfo_reflection_;
  delete FormationDataForGUI::default_instance_;
  delete FormationDataForGUI_reflection_;
}

void protobuf_AddDesc_Debug_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::protobuf_AddDesc_WorldInfo_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\013Debug.proto\032\017WorldInfo.proto\"7\n\026Locali"
    "zationDataForGUI\022\035\n\tParticles\030\001 \003(\0132\n.Ro"
    "botPose\"\202\001\n\014PositionInfo\022\t\n\001X\030\001 \002(\002\022\t\n\001Y"
    "\030\002 \002(\002\022\014\n\004role\030\003 \002(\005\"N\n\004ROLE\022\n\n\006GOALIE\020\000"
    "\022\014\n\010DEFENDER\020\001\022\n\n\006ONBALL\020\002\022\017\n\013SUPPORTER_"
    "L\020\003\022\017\n\013SUPPORTER_R\020\004\"7\n\023FormationDataFor"
    "GUI\022 \n\tPositions\030\001 \003(\0132\r.PositionInfo", 277);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "Debug.proto", &protobuf_RegisterTypes);
  LocalizationDataForGUI::default_instance_ = new LocalizationDataForGUI();
  PositionInfo::default_instance_ = new PositionInfo();
  FormationDataForGUI::default_instance_ = new FormationDataForGUI();
  LocalizationDataForGUI::default_instance_->InitAsDefaultInstance();
  PositionInfo::default_instance_->InitAsDefaultInstance();
  FormationDataForGUI::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_Debug_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_Debug_2eproto {
  StaticDescriptorInitializer_Debug_2eproto() {
    protobuf_AddDesc_Debug_2eproto();
  }
} static_descriptor_initializer_Debug_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int LocalizationDataForGUI::kParticlesFieldNumber;
#endif  // !_MSC_VER

LocalizationDataForGUI::LocalizationDataForGUI()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void LocalizationDataForGUI::InitAsDefaultInstance() {
}

LocalizationDataForGUI::LocalizationDataForGUI(const LocalizationDataForGUI& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void LocalizationDataForGUI::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

LocalizationDataForGUI::~LocalizationDataForGUI() {
  SharedDtor();
}

void LocalizationDataForGUI::SharedDtor() {
  if (this != default_instance_) {
  }
}

void LocalizationDataForGUI::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* LocalizationDataForGUI::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return LocalizationDataForGUI_descriptor_;
}

const LocalizationDataForGUI& LocalizationDataForGUI::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_Debug_2eproto();  return *default_instance_;
}

LocalizationDataForGUI* LocalizationDataForGUI::default_instance_ = NULL;

LocalizationDataForGUI* LocalizationDataForGUI::New() const {
  return new LocalizationDataForGUI;
}

void LocalizationDataForGUI::Clear() {
  particles_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool LocalizationDataForGUI::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .RobotPose Particles = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_Particles:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_particles()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(10)) goto parse_Particles;
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void LocalizationDataForGUI::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated .RobotPose Particles = 1;
  for (int i = 0; i < this->particles_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->particles(i), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* LocalizationDataForGUI::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated .RobotPose Particles = 1;
  for (int i = 0; i < this->particles_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->particles(i), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int LocalizationDataForGUI::ByteSize() const {
  int total_size = 0;
  
  // repeated .RobotPose Particles = 1;
  total_size += 1 * this->particles_size();
  for (int i = 0; i < this->particles_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->particles(i));
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void LocalizationDataForGUI::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const LocalizationDataForGUI* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const LocalizationDataForGUI*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void LocalizationDataForGUI::MergeFrom(const LocalizationDataForGUI& from) {
  GOOGLE_CHECK_NE(&from, this);
  particles_.MergeFrom(from.particles_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void LocalizationDataForGUI::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void LocalizationDataForGUI::CopyFrom(const LocalizationDataForGUI& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LocalizationDataForGUI::IsInitialized() const {
  
  for (int i = 0; i < particles_size(); i++) {
    if (!this->particles(i).IsInitialized()) return false;
  }
  return true;
}

void LocalizationDataForGUI::Swap(LocalizationDataForGUI* other) {
  if (other != this) {
    particles_.Swap(&other->particles_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata LocalizationDataForGUI::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = LocalizationDataForGUI_descriptor_;
  metadata.reflection = LocalizationDataForGUI_reflection_;
  return metadata;
}


// ===================================================================

const ::google::protobuf::EnumDescriptor* PositionInfo_ROLE_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PositionInfo_ROLE_descriptor_;
}
bool PositionInfo_ROLE_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const PositionInfo_ROLE PositionInfo::GOALIE;
const PositionInfo_ROLE PositionInfo::DEFENDER;
const PositionInfo_ROLE PositionInfo::ONBALL;
const PositionInfo_ROLE PositionInfo::SUPPORTER_L;
const PositionInfo_ROLE PositionInfo::SUPPORTER_R;
const PositionInfo_ROLE PositionInfo::ROLE_MIN;
const PositionInfo_ROLE PositionInfo::ROLE_MAX;
const int PositionInfo::ROLE_ARRAYSIZE;
#endif  // _MSC_VER
#ifndef _MSC_VER
const int PositionInfo::kXFieldNumber;
const int PositionInfo::kYFieldNumber;
const int PositionInfo::kRoleFieldNumber;
#endif  // !_MSC_VER

PositionInfo::PositionInfo()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void PositionInfo::InitAsDefaultInstance() {
}

PositionInfo::PositionInfo(const PositionInfo& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void PositionInfo::SharedCtor() {
  _cached_size_ = 0;
  x_ = 0;
  y_ = 0;
  role_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

PositionInfo::~PositionInfo() {
  SharedDtor();
}

void PositionInfo::SharedDtor() {
  if (this != default_instance_) {
  }
}

void PositionInfo::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PositionInfo::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PositionInfo_descriptor_;
}

const PositionInfo& PositionInfo::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_Debug_2eproto();  return *default_instance_;
}

PositionInfo* PositionInfo::default_instance_ = NULL;

PositionInfo* PositionInfo::New() const {
  return new PositionInfo;
}

void PositionInfo::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    x_ = 0;
    y_ = 0;
    role_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool PositionInfo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required float X = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &x_)));
          set_has_x();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(21)) goto parse_Y;
        break;
      }
      
      // required float Y = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_Y:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &y_)));
          set_has_y();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_role;
        break;
      }
      
      // required int32 role = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_role:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &role_)));
          set_has_role();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void PositionInfo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required float X = 1;
  if (has_x()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(1, this->x(), output);
  }
  
  // required float Y = 2;
  if (has_y()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->y(), output);
  }
  
  // required int32 role = 3;
  if (has_role()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->role(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* PositionInfo::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required float X = 1;
  if (has_x()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(1, this->x(), target);
  }
  
  // required float Y = 2;
  if (has_y()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->y(), target);
  }
  
  // required int32 role = 3;
  if (has_role()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->role(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int PositionInfo::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required float X = 1;
    if (has_x()) {
      total_size += 1 + 4;
    }
    
    // required float Y = 2;
    if (has_y()) {
      total_size += 1 + 4;
    }
    
    // required int32 role = 3;
    if (has_role()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->role());
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PositionInfo::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const PositionInfo* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const PositionInfo*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void PositionInfo::MergeFrom(const PositionInfo& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_x()) {
      set_x(from.x());
    }
    if (from.has_y()) {
      set_y(from.y());
    }
    if (from.has_role()) {
      set_role(from.role());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void PositionInfo::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PositionInfo::CopyFrom(const PositionInfo& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PositionInfo::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;
  
  return true;
}

void PositionInfo::Swap(PositionInfo* other) {
  if (other != this) {
    std::swap(x_, other->x_);
    std::swap(y_, other->y_);
    std::swap(role_, other->role_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata PositionInfo::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PositionInfo_descriptor_;
  metadata.reflection = PositionInfo_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int FormationDataForGUI::kPositionsFieldNumber;
#endif  // !_MSC_VER

FormationDataForGUI::FormationDataForGUI()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void FormationDataForGUI::InitAsDefaultInstance() {
}

FormationDataForGUI::FormationDataForGUI(const FormationDataForGUI& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void FormationDataForGUI::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

FormationDataForGUI::~FormationDataForGUI() {
  SharedDtor();
}

void FormationDataForGUI::SharedDtor() {
  if (this != default_instance_) {
  }
}

void FormationDataForGUI::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* FormationDataForGUI::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return FormationDataForGUI_descriptor_;
}

const FormationDataForGUI& FormationDataForGUI::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_Debug_2eproto();  return *default_instance_;
}

FormationDataForGUI* FormationDataForGUI::default_instance_ = NULL;

FormationDataForGUI* FormationDataForGUI::New() const {
  return new FormationDataForGUI;
}

void FormationDataForGUI::Clear() {
  positions_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool FormationDataForGUI::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .PositionInfo Positions = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_Positions:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_positions()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(10)) goto parse_Positions;
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void FormationDataForGUI::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated .PositionInfo Positions = 1;
  for (int i = 0; i < this->positions_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->positions(i), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* FormationDataForGUI::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated .PositionInfo Positions = 1;
  for (int i = 0; i < this->positions_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->positions(i), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int FormationDataForGUI::ByteSize() const {
  int total_size = 0;
  
  // repeated .PositionInfo Positions = 1;
  total_size += 1 * this->positions_size();
  for (int i = 0; i < this->positions_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->positions(i));
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void FormationDataForGUI::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const FormationDataForGUI* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const FormationDataForGUI*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void FormationDataForGUI::MergeFrom(const FormationDataForGUI& from) {
  GOOGLE_CHECK_NE(&from, this);
  positions_.MergeFrom(from.positions_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void FormationDataForGUI::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void FormationDataForGUI::CopyFrom(const FormationDataForGUI& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FormationDataForGUI::IsInitialized() const {
  
  for (int i = 0; i < positions_size(); i++) {
    if (!this->positions(i).IsInitialized()) return false;
  }
  return true;
}

void FormationDataForGUI::Swap(FormationDataForGUI* other) {
  if (other != this) {
    positions_.Swap(&other->positions_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata FormationDataForGUI::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = FormationDataForGUI_descriptor_;
  metadata.reflection = FormationDataForGUI_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
