// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "ObstacleAvoidanceMessage.pb.h"
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* ObstacleMessage_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ObstacleMessage_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_ObstacleAvoidanceMessage_2eproto() {
  protobuf_AddDesc_ObstacleAvoidanceMessage_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "ObstacleAvoidanceMessage.proto");
  GOOGLE_CHECK(file != NULL);
  ObstacleMessage_descriptor_ = file->message_type(0);
  static const int ObstacleMessage_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ObstacleMessage, direction_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ObstacleMessage, distance_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ObstacleMessage, certainty_),
  };
  ObstacleMessage_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ObstacleMessage_descriptor_,
      ObstacleMessage::default_instance_,
      ObstacleMessage_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ObstacleMessage, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ObstacleMessage, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ObstacleMessage));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_ObstacleAvoidanceMessage_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ObstacleMessage_descriptor_, &ObstacleMessage::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_ObstacleAvoidanceMessage_2eproto() {
  delete ObstacleMessage::default_instance_;
  delete ObstacleMessage_reflection_;
}

void protobuf_AddDesc_ObstacleAvoidanceMessage_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\036ObstacleAvoidanceMessage.proto\"R\n\017Obst"
    "acleMessage\022\024\n\tdirection\030\001 \002(\005:\0010\022\023\n\010dis"
    "tance\030\002 \002(\002:\0010\022\024\n\tcertainty\030\003 \002(\002:\0010", 116);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "ObstacleAvoidanceMessage.proto", &protobuf_RegisterTypes);
  ObstacleMessage::default_instance_ = new ObstacleMessage();
  ObstacleMessage::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_ObstacleAvoidanceMessage_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_ObstacleAvoidanceMessage_2eproto {
  StaticDescriptorInitializer_ObstacleAvoidanceMessage_2eproto() {
    protobuf_AddDesc_ObstacleAvoidanceMessage_2eproto();
  }
} static_descriptor_initializer_ObstacleAvoidanceMessage_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int ObstacleMessage::kDirectionFieldNumber;
const int ObstacleMessage::kDistanceFieldNumber;
const int ObstacleMessage::kCertaintyFieldNumber;
#endif  // !_MSC_VER

ObstacleMessage::ObstacleMessage()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void ObstacleMessage::InitAsDefaultInstance() {
}

ObstacleMessage::ObstacleMessage(const ObstacleMessage& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void ObstacleMessage::SharedCtor() {
  _cached_size_ = 0;
  direction_ = 0;
  distance_ = 0;
  certainty_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ObstacleMessage::~ObstacleMessage() {
  SharedDtor();
}

void ObstacleMessage::SharedDtor() {
  if (this != default_instance_) {
  }
}

void ObstacleMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ObstacleMessage::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ObstacleMessage_descriptor_;
}

const ObstacleMessage& ObstacleMessage::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_ObstacleAvoidanceMessage_2eproto();  return *default_instance_;
}

ObstacleMessage* ObstacleMessage::default_instance_ = NULL;

ObstacleMessage* ObstacleMessage::New() const {
  return new ObstacleMessage;
}

void ObstacleMessage::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    direction_ = 0;
    distance_ = 0;
    certainty_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ObstacleMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 direction = 1 [default = 0];
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &direction_)));
          _set_bit(0);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(21)) goto parse_distance;
        break;
      }
      
      // required float distance = 2 [default = 0];
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_distance:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &distance_)));
          _set_bit(1);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(29)) goto parse_certainty;
        break;
      }
      
      // required float certainty = 3 [default = 0];
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_certainty:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &certainty_)));
          _set_bit(2);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void ObstacleMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int32 direction = 1 [default = 0];
  if (_has_bit(0)) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->direction(), output);
  }
  
  // required float distance = 2 [default = 0];
  if (_has_bit(1)) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->distance(), output);
  }
  
  // required float certainty = 3 [default = 0];
  if (_has_bit(2)) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(3, this->certainty(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* ObstacleMessage::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int32 direction = 1 [default = 0];
  if (_has_bit(0)) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->direction(), target);
  }
  
  // required float distance = 2 [default = 0];
  if (_has_bit(1)) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->distance(), target);
  }
  
  // required float certainty = 3 [default = 0];
  if (_has_bit(2)) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(3, this->certainty(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int ObstacleMessage::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 direction = 1 [default = 0];
    if (has_direction()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->direction());
    }
    
    // required float distance = 2 [default = 0];
    if (has_distance()) {
      total_size += 1 + 4;
    }
    
    // required float certainty = 3 [default = 0];
    if (has_certainty()) {
      total_size += 1 + 4;
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ObstacleMessage::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ObstacleMessage* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ObstacleMessage*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ObstacleMessage::MergeFrom(const ObstacleMessage& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from._has_bit(0)) {
      set_direction(from.direction());
    }
    if (from._has_bit(1)) {
      set_distance(from.distance());
    }
    if (from._has_bit(2)) {
      set_certainty(from.certainty());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ObstacleMessage::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ObstacleMessage::CopyFrom(const ObstacleMessage& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ObstacleMessage::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;
  
  return true;
}

void ObstacleMessage::Swap(ObstacleMessage* other) {
  if (other != this) {
    std::swap(direction_, other->direction_);
    std::swap(distance_, other->distance_);
    std::swap(certainty_, other->certainty_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ObstacleMessage::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ObstacleMessage_descriptor_;
  metadata.reflection = ObstacleMessage_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
