/**
 * @author Cbm
 *
 * This file was generated by Aldebaran Robotics ModuleGenerator
 */

#ifndef KROBOT_MAINMODULE_H
#define KROBOT_MAINMODULE_H

#include <alcore/alptr.h>
#include <alcommon/almodule.h>

#include "architecture/talws.h"

namespace AL
{
  class ALBroker;
}

/**
 * DESCRIBE YOUR CLASS HERE
 */
class mainModule : public AL::ALModule
{

  public:

    /**
     * Default Constructor.
     */
     mainModule(AL::ALPtr<AL::ALBroker> pBroker, const std::string& pName );

    /**
     * Destructor.
     */
    virtual ~mainModule();


    void Start();

    void Stop();

  private:

    Talws* tal;

};

#endif  // KROBOT_MAINMODULE_H

