
set(ProtobufPrebuild  ${ConfigDir}/${TargetPlatform}/lib/${CMAKE_SYSTEM_PROCESSOR}/libprotobuf.a)
message( STATUS ${ConfigDir}/${TargetPlatform}/lib/${CMAKE_SYSTEM_PROCESSOR}/libprotobuf.a)
if(EXISTS ${ProtobufPrebuild})
	set( ProtobufLibrary ${ProtobufPrebuild})
else()
	find_package(Protobuf)
	message(STATUS ${PROTOBUF_LIBRARY})
	set( ProtobufLibrary ${PROTOBUF_LIBRARY})
endif()
message ( STATUS "Protobuf lib path: ${ProtobufLibrary}")
