#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# launch background task of naoqi (sentinel, urbi, ...)
# syntax: scriptname <nao_ip>
#
# Author: A. Mazel

# TODO: use the python module "option" to parse command line

print( "###### behavior - started" );
import os
import sys
import naoqi
import time
from naoqi import ALProxy

IP = "127.0.0.1"#"nao57.local"#
PORT = 9559

def main():

    while(True):
      try:
        proxy = ALProxy("mainModule", IP, PORT)
        proxy.post.Start()
        return
      except:
        time.sleep(0.5)

if __name__ == "__main__":
    main()
