#!/bin/sh

DAEMON=/usr/sbin/connmand
PIDFILE=/var/run/connmand.pid
DESC="Connection Manager"

if [ -f /var/lib/connman/default.profile ];then
        sed -i "/^Failure/d" /var/lib/connman/default.profile
fi

if [ -f /etc/default/connman ] ; then
	. /etc/default/connman
fi

set -e

do_start() {
        if [ -f /home/nao/naoqi/config/connman.profile ]; then
        	echo "Applying profile /home/nao/naoqi/config/connman.profile"
                rm /var/lib/connman/default.profile
                cp /home/nao/naoqi/config/connman.profile /var/lib/connman/default.profile
        fi
	$DAEMON
}

do_stop() {
	start-stop-daemon --stop --name connmand --quiet
}

case "$1" in
  start)
	echo "Starting $DESC"
	do_start
	;;
  stop)
	echo "Stopping $DESC"
	do_stop
	;;
  restart|force-reload)
	echo "Restarting $DESC"
	do_stop
	sleep 1
	do_start
	;;
  *)
	echo "Usage: $0 {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
